name: Integration Test
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      # Replace this step with your custom versioning script
      - name: Get Versioning Data
        id: versioning
        run: |
          # Run your custom versioning script here
          # Example:
          echo "::set-output name=tag::$(./custom_versioning_script.sh)"
          echo "::set-output name=changelog::$(./custom_versioning_script.sh changelog)"

      - name: Create Release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ github.event.head_commit.message }}
          tag: ${{ steps.versioning.outputs.tag }}
          body: "${{ steps.versioning.outputs.changelog }}"
          gzip: false
